version: "3"
services:
  base: &base
    image: yangcheng2503/sbt-base:graalvm
    working_dir: /app
    volumes:
      - ".:/app"
      - ~/.cache:/root/.cache
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
    entrypoint: bash

  test:
    <<: *base
    entrypoint: sbt test

  build-native-image:
    <<: *base
    entrypoint: sbt ni
